title: "WD South"
description: "Online Writing Archive"
# Site settings
permalink: /:title/
markdown: kramdown
paginate: 5
paginate_path: "/:num/"
date_format: "%b %-d, %Y"

# add includes, remote themes, plugins here.
include: [".well-known"]
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # adds remote themes.
- jekyll-feed # atom (rss-like) feed generator. 
- jekyll-paginate #pagination plugin.
- jekyll-seo-tag  #SEO for tags.
- jekyll-sitemap #Generate site-map.  
